# Generated by Django 4.1.7 on 2023-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('amh', 'Amharic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='agency',
            name='time_zone',
            field=models.CharField(choices=[('+3', 'UTC+3')], max_length=200),
        ),
    ]
