# Generated by Django 4.1.7 on 2023-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('shape_pt_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shape_pt_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shape_pt_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
