# Generated by Django 4.1.7 on 2023-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='shape_id',
            field=models.CharField(default='default_shape', max_length=200),
        ),
    ]
