# Generated by Django 4.1.7 on 2023-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_alter_shape_shape_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='shape_id',
        ),
        migrations.AlterField(
            model_name='shape',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
