# Generated by Django 4.1.7 on 2023-06-13 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0003_remove_shape_shape_id_alter_shape_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
