---
version: '3.8'

services:
  db:
    restart: unless-stopped
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: sh -c "python ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    restart: unless-stopped
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - 3000:3000
volumes:
  postgres_data: