# Generated by Django 4.1.7 on 2023-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='service_id',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
