# Generated by Django 4.1.7 on 2023-06-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_alter_agency_id'),
        ('calendars', '0002_calendar_service_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('agency', 'start_date')},
        ),
    ]
