# Generated by Django 4.1.7 on 2023-03-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('stops', '0002_remove_stop_parent_station'),
        ('stop_times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stops.stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
            preserve_default=False,
        ),
    ]
