# Generated by Django 4.1.7 on 2023-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_times', '0002_stoptime_stop_stoptime_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='timepoint',
            field=models.IntegerField(default=0),
        ),
    ]
