# Generated by Django 4.1.7 on 2023-06-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_route_trip_shape_alter_trip_id'),
        ('stop_times', '0003_stoptime_timepoint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('stop_sequence', 'trip')},
        ),
    ]
