# Generated by Django 4.1.7 on 2023-06-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_route_trip_shape_alter_trip_id'),
        ('stop_times', '0004_alter_stoptime_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('trip', 'stop_sequence')},
        ),
    ]
