# Generated by Django 4.1.7 on 2023-06-12 04:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delay', models.DurationField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('uncertainty', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopTimeUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stop_sequence', models.IntegerField()),
                ('stop_id', models.CharField(max_length=100)),
                ('schedule_relationship', models.IntegerField(blank=True, choices=[(0, 'SCHEDULED'), (1, 'SKIPPED'), (2, 'NO_DATA')], null=True)),
                ('arrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='trip_updater.stoptimeevent')),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='trip_updater.stoptimeevent')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('timestamp', models.TimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(editable=False, max_length=200, unique=True)),
                ('route_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('schedule_relationship', models.IntegerField(choices=[(0, 'SCHEDULED'), (1, 'ADDED'), (2, 'UNSCHEDULED'), (3, 'CANCELED')])),
                ('stop_time_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_time_update', to='trip_updater.stoptimeupdate')),
            ],
        ),
    ]
