# Generated by Django 4.1.7 on 2023-04-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_entity', models.CharField(choices=[('route', 'route'), ('agency', 'agency'), ('trip', 'trip')], max_length=40)),
                ('entity_id', models.UUIDField()),
                ('cause', models.IntegerField(choices=[(1, 'UNKNOWN_CAUSE'), (2, 'OTHER_CAUSE'), (3, 'TECHNICAL_PROBLEM'), (4, 'STRIKE'), (5, 'DEMONSTRATION'), (6, 'ACCIDENT'), (7, 'HOLIDAY'), (8, 'WEATHER'), (9, 'MAINTENANCE'), (10, 'CONSTRUCTION'), (11, 'POLICE_ACTIVITY'), (12, 'MEDICAL_EMERGENCY')])),
                ('effect', models.IntegerField(choices=[(1, 'NO_SERVICE'), (2, 'REDUCED_SERVICE'), (3, 'SIGNIFICANT_DELAYS'), (4, 'DETOUR'), (5, 'ADDITIONAL_SERVICE'), (6, 'MODIFIED_SERVICE'), (7, 'OTHER_EFFECT'), (8, 'UNKNOWN_EFFECT'), (9, 'STOP_MOVED')])),
                ('duration', models.DurationField()),
                ('start_timestamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('timestamp', models.TimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
