# Generated by Django 4.1.7 on 2023-06-07 16:38

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('updater', 'Alert')
    for row in MyModel.objects.all():
        row.alert_feed_id = uuid.uuid4()
        row.save(update_fields=['alert_feed_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0002_alert_alert_feed_id_alter_alert_start_timestamp'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
