# Generated by Django 4.1.7 on 2023-06-07 16:38

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0003_auto_20230607_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_feed_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
