# Generated by Django 4.1.7 on 2023-06-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0004_auto_20230607_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='start_timestamp',
        ),
    ]
