# Generated by Django 4.1.7 on 2023-06-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_alter_agency_admin"),
        ("trips", "0001_initial"),
        ("routes", "0001_initial"),
        ("updater", "0006_alert_start_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="entity_id",
        ),
        migrations.AddField(
            model_name="alert",
            name="agency_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agencies.agency",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="message",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="route_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.route",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="trip_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trips.trip",
            ),
        ),
    ]
