# Generated by Django 4.1.7 on 2023-06-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0007_remove_alert_entity_id_alert_agency_id_alert_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleupdate',
            name='trip',
        ),
    ]
