# Generated by Django 4.1.7 on 2023-06-15 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stop_times', '0005_alter_stoptime_unique_together'),
        ('trips', '0003_alter_trip_id'),
        ('updater', '0008_remove_vehicleupdate_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_update_feed_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('delay', models.DurationField()),
                ('trip_update_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('stop_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop_times.stoptime')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
