# Generated by Django 4.1.7 on 2023-06-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_id'),
        ('shapes', '0002_alter_shape_shape_id'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='shape',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shapes.shape'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
