# Generated by Django 4.1.7 on 2023-03-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_remove_stop_parent_station'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stops', to='stops.stop'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stops', to='stops.stop'),
        ),
    ]
