# Generated by Django 4.1.7 on 2023-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
