# Generated by Django 4.1.7 on 2023-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_admin_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='otp_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
