# Generated by Django 4.1.7 on 2023-03-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_desc', models.CharField(max_length=500)),
                ('stop_code', models.CharField(max_length=50)),
                ('stop_lat', models.CharField(max_length=50)),
                ('stop_long', models.CharField(max_length=50)),
                ('stop_url', models.URLField()),
                ('location_type', models.CharField(choices=[('dkn', "don't know"), ('now', 'dont')], max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.stop')),
            ],
        ),
    ]
